### ISSUE TITLE
Terms of Services

### ISSUE THREAD

**Issue by ashledombos** [OpenMandrivaSoftware/rosa-build#10]
Hi,

Is it possible to add somewhere a link to our TOS in ABF? (can be anywhere, at the bottom or else):
https://www.openmandriva.org/tos

**Comment by avokhmin** [comment]
@ashledombos , done, can you recheck?

**Comment by ashledombos** [comment]
Thank you @avokhmin :)

**Comment by avokhmin** [comment]
ok, closed.
