### ISSUE TITLE
Increase release tag does not work

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/rosa-build#22]
When you start a mass rebuild with "Increase release tag" set to true then mass rebuild seems to fails.
Ofcourse packages sources on github from mass rebuild are not touched by ABF :(

Sounds like and issue with https://github.com/abf-repo-bot

**Comment by tpgxyz** [comment]
See these mass rebuilds
https://abf.openmandriva.org/platforms/cooker/mass_builds/125
https://abf.openmandriva.org/platforms/cooker/mass_builds/124

**Comment by avokhmin** [comment]
@tpgxyz , 

> https://abf.openmandriva.org/platforms/cooker/mass_builds/125
> https://abf.openmandriva.org/platforms/cooker/mass_builds/124

here is 0 build lists.

Also, I found that we forgot to set `GITHUB_APP_ID ` (when I tried to login via Github => fail), so, maybe need to add this keys and all will start to work? 

See: 

![screen shot 2018-03-20 at 10 57 12](https://user-images.githubusercontent.com/422109/37644784-8bd02be4-2c2d-11e8-9898-ae7d17559d79.PNG)

**Comment by tpgxyz** [comment]
Ok it works now

https://github.com/OpenMandrivaAssociation/null/commit/6c3d8985ce4dc85d10a837768694086390bff405
