### ISSUE TITLE
Mobile site is not useable

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/rosa-build#3]
Previous UI was working fine on mobile phones. With new UI it is impossible to browse ABF not to mention to do some operations (build, change settings etc).

Looks like work is needed on RWD.

@fedya  @DuratarskeyK

**Comment by DuratarskeyK** [comment]
I fixed the nav panel on the login page and it looks like I can create a new build from my phone. What else needs fixing?

**Comment by tpgxyz** [comment]
Here are few suggestions:

1. Statisctics graph looks ugly - i'd disable diplaying it on displays less thatn 760px
2. By default zoom scale for site is too big, i'd reduce it about 20%
3. Left blue panel is too big. Either it is full screen, and after choosing some option panel goes to minimal mode or it is scaled to 30% of screen
4. On build lists a buttons (filters, update page..) are displayed off the frame and they seems to be wrongly wrapped

**Comment by DuratarskeyK** [comment]
I have fixed the menu somewhat, how does it look now?

**Comment by tpgxyz** [comment]
Menu looks better, but imho when it is unfolded then it takes too much space on screen.

Try in firefox ctrl+shift+m and change resolution to 320x480 :)

**Comment by DuratarskeyK** [comment]
But I don't know, how to squeze it more, what if I always hide it at the start?

**Comment by tpgxyz** [comment]
Hiding on start sounds good idea :)

**Comment by tpgxyz** [comment]
Seems to be fixed
